name: Deploy
on:
  push:
    branches:
      - main
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::108929950724:role/GithubRole
          aws-region: us-east-1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: jim-brighter/github-release-action@v4
        with:
          major-version: 1
          minor-version: 0
          num_releases_to_keep: 10
      - name: Deploy
        run: |
          cd cdk
          npm i
          npm run deploy
